CREATE TABLE HOROSCOPO 
(
  ANIMAL VARCHAR2(30 BYTE) 
, FECHA_INICIO DATE 
, FECHA_FIN DATE 
) 

CREATE TABLE USUARIOS 
(
  ID NUMBER NOT NULL 
, NOMBRE VARCHAR2(30 BYTE) 
, USERNAME VARCHAR2(30 BYTE) 
, EMAIL VARCHAR2(30 BYTE) 
, FECHA_NACIMIENTO DATE 
, PASSWORD VARCHAR2(30 BYTE) 
, ANIMAL VARCHAR2(30 BYTE) 
, CONSTRAINT PK_USER PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX PK_USER ON USUARIOS (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;




---Creacion de secuencia para generar id

   CREATE SEQUENCE  "FINAL_DRILLING"."SQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;


---Creacion de Triger para controlar secuencia
create or replace TRIGGER TG_SQ_TABLA_USUARIOS
BEFORE INSERT ON USUARIOS
FOR EACH ROW

DECLARE



BEGIN
    :NEW.ID:= SQ_USUARIOS.NEXTVAL;
END;


